{% set version = "13.1.1" %}

package:
  name: cuda-runtime
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  # This is 'technically' not a noarch package: only supported on linux-64, linux-aarch64 and windows-64
  # Therefore, 'noarch: generic' is replaced with 'skip: true' to avoid building on unsupported platforms.
  skip: true  # [osx]

requirements:
  run:
    # Remove '__linux' and '__win' as they might not be handled properly on PBP
    # Also, see above note about 'skip: true'
    - cuda-libraries {{ version }}

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all runtime library packages.
  description: |
    Meta-package containing all runtime library packages.
  doc_url: https://docs.nvidia.com/cuda/index.html
  dev_url: https://docs.nvidia.com/cuda/index.html

extra:
  skip-lints:
    - license_file_overspecified
  recipe-maintainers:
    - conda-forge/cuda
